# Generated by Django 4.1.2 on 2022-10-28 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_artiste_lyric_song_delete_school_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='score_id',
            new_name='song_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='date',
        ),
        migrations.AddField(
            model_name='song',
            name='date_released',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
